### PR TITLE
Fix `vcfwave` and its behavior with inversions

### LINKED ISSUE #370: `vcfwave` does not behave as expected with inversions
With this VCF file:

```
cat x.vcf | column -t

##fileformat=VCFv4.2                                                                                                                                                                                                 
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">                                                                                                                                                         
##contig=<ID=TAIR10#1#chr1,length=30427671>                                                                                                                                                                          
#CHROM         POS  ID  REF                             ALT                             QUAL  FILTER  INFO  FORMAT  AT1741#1  AT5784#1  AT6909#1  AT6911#1  AT7186#1  AT7213#1
TAIR10#1#chr1  711  .   TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA  60    .       .     GT      1         1         1         1         1         1
TAIR10#1#chr1  892  .   TTTTATTTT                       TTTTGTTTT                       60    .       .     GT      1         1         1         1         1         1
```

I get an error with the current master:

```
./vcfwave x.vcf --inv-min 20 -K 3 -k

##fileformat=VCFv4.2
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##contig=<ID=TAIR10#1#chr1,length=30427671>
##INFO=<ID=TYPE,Number=A,Type=String,Description="The type of allele, either snp, mnp, ins, del, or complex.">
##INFO=<ID=LEN,Number=A,Type=Integer,Description="allele length">
##INFO=<ID=ORIGIN,Number=1,Type=String,Description="Decomposed from a complex record using vcflib vcfwave and alignment with WFA2-lib.">
##INFO=<ID=INV,Number=A,Type=String,Description="Count of haplotypes which are aligned in the inverted orientation using vcflib vcfwave.">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	AT1741#1	AT5784#1	AT6909#1	AT6911#1	AT7186#1	AT7213#1
vcfwave 1.0.7 processing...
terminate called after throwing an instance of 'std::out_of_range'█████████▏	                          
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
[1]    41137 IOT instruction (core dumped)  ./vcfwave x.vcf ---inv-min 20 -K 3 -k
```

Instead, with the version that we still use in `pggb` (commit 4f2bce873bc520449ec549f36aaaad65bace51ca), I correctly get the SNP in position 896, but lose the first variant:

```
./vcfwave x.vcf --inv-min 20 -K 3 -k

##fileformat=VCFv4.2
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##contig=<ID=TAIR10#1#chr1,length=30427671>
##INFO=<ID=TYPE,Number=A,Type=String,Description="The type of allele, either snp, mnp, ins, del, or complex.">
##INFO=<ID=LEN,Number=A,Type=Integer,Description="allele length">
##INFO=<ID=ORIGIN,Number=1,Type=String,Description="Decomposed from a complex record using vcflib vcfwave and alignment with WFA2-lib.">
##INFO=<ID=INV,Number=A,Type=String,Description="Count of haplotypes which are aligned in the inverted orientation using vcflib vcfwave.">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	AT1741#1	AT5784#1	AT6909#1	AT6911#1	AT7186#1	AT7213#1
TAIR10#1#chr1	896	._1	A	G	60	.	INV=0;LEN=1;ORIGIN=TAIR10#1#chr1:892;TYPE=snp	GT	1	1	1	1	1	1
```
[x.vcf.gz](https://github.com/vcflib/vcflib/files/11035506/x.vcf.gz)

### PR DESCRIPTION
**Pull request by AndreaGuarracino**
Trying to fix https://github.com/vcflib/vcflib/issues/370.

Now we avoid the error, but I still get strange behaviors with the inversions.

### CODE REVIEW

**Comment by AndreaGuarracino** [comment]
It seems that it is a 'feature':

```shell
grep '^##' -v x.vcf | column -t

#CHROM  POS  ID   REF                             ALT                              QUAL  FILTER  INFO  FORMAT  A  B
Z       100  ID1  TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA   60    .       .     GT      1  1
Z       200  ID2  TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT  AAAAAAACAAATAAATAAAAAAAAAAAAAAA  60    .       .     GT      1  1
Z       300  ID3  TTTTTTTTTTTTTTTAAAAAAAAAAAAAAA  AAAAAAAAAAAAAAATTTTTTTTTTTTTTT   60    .       .     GT      1  1

vcfwave x.vcf --inv-min 20 -K 3 -k -q | grep '^##' -v | column -t
#CHROM  POS  ID     REF               ALT               QUAL  FILTER  INFO                                FORMAT  A  B
Z       214  ID2_1  T                 TA                60    .       ORIGIN=Z:200;LEN=1;INV=1;TYPE=ins   GT      1  1
Z       218  ID2_2  T                 A                 60    .       ORIGIN=Z:200;LEN=1;INV=1;TYPE=snp   GT      1  1
Z       222  ID2_3  T                 G                 60    .       ORIGIN=Z:200;LEN=1;INV=1;TYPE=snp   GT      1  1
Z       300  ID3_1  T                 AAAAAAAAAAAAAAAT  60    .       ORIGIN=Z:300;LEN=15;INV=0;TYPE=ins  GT      1  1
Z       314  ID3_2  TAAAAAAAAAAAAAAA  T                 60    .       ORIGIN=Z:300;LEN=15;INV=0;TYPE=del  GT      1  1
```

- Variant `ID1` is a perfect inversion, so by aligning the reverse complement of the alternate allele (`AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA` -> `TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT`) against the reference allele (`TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT`), we get a perfect match, so no variants are written in the VCF file. In this way, we lose such an inversion.
- Variant `ID2` is not a perfect inversion, and it leads to INDELS and SNPs that are annotated as inversions. I am not sure this is the correct way to annotate the SNPs.
- Variant `ID3` is not an inversion, that implies reverse and complement: here we just have as an alternate allele the reversed (not complemented) sequence of the reference allele.

**Comment by AndreaGuarracino** [comment]
Another thing that confuses me is that in the decomposed VCF file we can find alleles that are not really directly present in the original sequence (G at position 222 with respect to the reference).

**Comment by pjotrp** [comment]
Looks good. Do you mind adding a test case?

**Comment by AndreaGuarracino** [comment]
I've fixed the problem by just reporting the presence of an inversion:

```shell
./vcfwave ~/vcflib/samples/test-vcfwave.small.vcf --inv-min 20 -K 3 -k -q  | grep '##' -v | column -t   
#CHROM  POS  ID     REF                             ALT                              QUAL  FILTER  INFO                                  FORMAT  A  B
Z       100  ID1    TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA   60    .       ORIGIN=Z:100;LEN=30;INV=YES;TYPE=mnp  GT      1  1
Z       200  ID2    TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT  AAAAAAACAAATAAATAAAAAAAAAAAAAAA  60    .       ORIGIN=Z:200;LEN=1;INV=YES;TYPE=ins   GT      1  1
Z       300  ID3_1  T                               AAAAAAAAAAAAAAAT                 60    .       ORIGIN=Z:300;LEN=15;TYPE=ins          GT      1  1
Z       314  ID3_2  TAAAAAAAAAAAAAAA                T                                60    .       ORIGIN=Z:300;LEN=15;TYPE=del          GT      1  1
```

**Comment by pjotrp** [comment]
I agree we should disable this 'feature' until it is better thought out. If someone wants to have a stab at it... I'll add an issue to the tracker.

Thanks @AndreaGuarracino for adding the test too. So, essentially we are ignoring aligning the reverse complement because it was giving the wrong results in the 'downstream' processing of vcfwave.cpp. You have added an inversion flag for annotation.

**Pull request merged**
