### PR TITLE
Fix MacOS Build: Update WFA2-lib

### LINKED ISSUE #377: Build broken on Mac OS due to VERSION file in WFA2_lib
**Describe the bug**

The currently bundled version of WFA2-lib has a file in its root called VERSION that leads to a build failure on Mac OS, because of the case-insensitive filesystem.

It was fixed here a few weeks ago:
https://github.com/smarco/WFA2-lib/issues/62

The simplest fix is to update to a hewer WFA2-lib, but I see there hasn't been a versioned release since this fix.

**To Reproduce**

Attempt a clean clone and build on any Mac OS with a case-insensitive filesystem, which is the default.
```
git clone --recursive https://github.com/vcflib/vcflib.git
cd vcflib
mkdir -p build && cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DZIG=OFF -DOPENMP=OFF ..
cmake --build .
cmake --install .
```

See dozens of failures caused by `#include <version>` within Apple's C++ distribution finding the `VERSION` file in wfa2_lib:
```
In file included from /Users/alex/src/vcflib/src/vcf-c-api.cpp:9:
In file included from /Users/alex/src/vcflib/src/Variant.h:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/vector:274:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/copy.h:12:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__algorithm/unwrap_iter.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__iterator/iterator_traits.h:14:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__iterator/incrementable_traits.h:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/concepts:133:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__concepts/arithmetic.h:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/type_traits:421:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__functional/invoke.h:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__type_traits/apply_cv.h:16:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/__type_traits/remove_reference.h:13:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/c++/v1/cstddef:42:
/Users/alex/src/vcflib/contrib/WFA2-lib/version:1:1: fatal error: unknown type name 'v2'
```

**Expected behavior**

vcflib should be buildable on Mac OS.

### PR DESCRIPTION
**Pull request by pettyalex**
Update WFA2-lib to a newer version that will allow vcflib to compile on Mac OS.

This fixes https://github.com/vcflib/vcflib/issues/377.

The only downside is that this relies on a specific commit on WFA2-lib and not a versioned release.

### CODE REVIEW

**Comment by pettyalex** [comment]
The latest master branch of WFA2-lib can't build with OpenMP, so I'm rolling back to an older commit.

https://github.com/smarco/WFA2-lib/issues/67

**Comment by pettyalex** [comment]
OK! WFA2-lib merged my fix, so I'm updating this to the latest version.

This seems to fix https://github.com/vcflib/vcflib/issues/350, as I'm now able to do a build with default apple clang on Mac OS. I do have libomp installed from brew.

**Comment by pjotrp** [comment]
Thanks! I'll work with upstream to get it in.

**Comment by pjotrp** [comment]
I think it was merged upstream. Can you update the PR so I can give you credit?

**Comment by pjotrp** [comment]
Thanks for the fixes. I'll look at this one.

**Comment by mr-c** [comment]
Ping :-) We'd like to know if we can safely update wfa2-lib in Debian.

**Comment by pjotrp** [comment]
Latest release builds against latest wfa2lib.

**Pull request closed without merging**
