### PR TITLE
Fix man page installation

### PR DESCRIPTION
**Pull request by alexreg**
The trailing slash in `${CMAKE_SOURCE_DIR}/man/` is important, as we do not want to install the man pages in `${CMAKE_INSTALL_PREFIX}/man/man1/man`, but rather just `${CMAKE_INSTALL_PREFIX}/man/man1`. (I encountered this problem when building on macOS.)

Per the [documentation](https://cmake.org/cmake/help/latest/command/install.html):

> The DIRECTORY form installs contents of one or more directories to a given destination. The directory structure is copied verbatim to the destination. The last component of each directory name is appended to the destination directory but a trailing slash may be used to avoid this because it leaves the last component empty.

### CODE REVIEW

**Comment by pjotrp** [comment]
Thank you!

**Comment by alexreg** [comment]
No problem. Thanks for merging.

**Comment by alexreg** [comment]
Do you think you'll be able to make a v1.0.3 release soon?

**Comment by pjotrp** [comment]
We should in the coming weeks.

**Pull request merged**
