### PR TITLE
Added -k flag for keeping info in genotype filtering, instead of a '.'

### PR DESCRIPTION
**Pull request by josephliccini**

### CODE REVIEW

**Comment by ekg** [comment]
@josephliccini This is awesome! But... would you mind removing your eclipse-specific hidden files from the pull request? Is there any reason you'd like to include them?

**Comment by josephliccini** [comment]
Ah shoot, my bad. I'll remove those once I get to class!

**Comment by josephliccini** [comment]
should be fixed up, let me know if there are any issues!

**Comment by ekg** [comment]
Done and done. Great job.

**Pull request merged**
